{{-- resources/views/admin/score-entry/marksheet-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Marks Sheet - {{ $classInfo->subject ?? '' }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Segoe UI', Arial, sans-serif;
            font-size: 10px;
            line-height: 1.4;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1e3a5f;
            padding-bottom: 10px;
        }
        .school-name {
            font-size: 18px;
            font-weight: bold;
            color: #1e3a5f;
            margin-bottom: 5px;
        }
        .school-address {
            font-size: 10px;
            color: #666;
        }
        .title {
            font-size: 14px;
            font-weight: bold;
            margin: 15px 0;
            text-align: center;
            background: #1e3a5f;
            color: white;
            padding: 8px;
        }
        .info-table {
            width: 100%;
            margin-bottom: 15px;
            border-collapse: collapse;
        }
        .info-table td {
            padding: 4px;
            border: none;
        }
        .scores-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .scores-table th {
            background: #1e3a5f;
            color: white;
            padding: 6px 4px;
            border: 1px solid #ddd;
            font-size: 9px;
            text-align: center;
        }
        .scores-table td {
            border: 1px solid #ddd;
            padding: 5px 4px;
            text-align: center;
            font-size: 9px;
        }
        .scores-table td:first-child,
        .scores-table th:first-child {
            text-align: left;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .signature {
            margin-top: 30px;
            display: flex;
            justify-content: space-between;
        }
        .admin-note {
            background: #fef3c7;
            border-left: 3px solid #d97706;
            padding: 6px 10px;
            margin-bottom: 15px;
            font-size: 9px;
        }
        .grade-A { background: #dcfce7; }
        .grade-B { background: #dbeafe; }
        .grade-C { background: #fef3c7; }
        .grade-D { background: #fed7aa; }
        .grade-F { background: #fee2e2; }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ $school->schoolname ?? 'School Name' }}</div>
        <div class="school-address">{{ $school->address ?? '' }}</div>
    </div>

    <div class="admin-note">
        <strong>📋 Admin Generated Report</strong> - This marks sheet was generated by an administrator on behalf of the subject teacher.
    </div>

    <div class="title">
        {{ strtoupper($classInfo->subject ?? '') }} ({{ $classInfo->subject_code ?? '' }}) - MARKS SHEET
    </div>

    <table class="info-table">
        <tr>
            <td width="50%"><strong>Class:</strong> {{ $classInfo->schoolclass ?? '' }} {{ $classInfo->arm ?? '' }}</td>
            <td width="50%"><strong>Term:</strong> {{ $classInfo->term ?? '' }}</td>
        </tr>
        <tr>
            <td><strong>Session:</strong> {{ $classInfo->session ?? '' }}</td>
            <td><strong>Teacher:</strong> {{ $teacherName ?? 'N/A' }} <span style="color:#d97706;">(Entered by Admin)</span></td>
        </tr>
    </table>

    <table class="scores-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Admission No</th>
                <th>Student Name</th>
                @foreach($assessments as $assessment)
                    <th>{{ $assessment->name }}<br>({{ $assessment->max_score }})</th>
                @endforeach
                <th>Total</th>
                <th>Grade</th>
                <th>Cum</th>
                <th>Position</th>
            </tr>
        </thead>
        <tbody>
            @foreach($broadsheets as $index => $b)
                @php
                    $rowTotal = 0;
                    $assessmentScores = [];
                    foreach($assessments as $a) {
                        $so = $b->assessmentScores->where('assessment_id', $a->id)->first();
                        $score = $so ? $so->score : 0;
                        $rowTotal += $score;
                        $assessmentScores[$a->id] = $score;
                    }
                    $gradeClass = match($b->grade) {
                        'A', 'A1' => 'grade-A',
                        'B', 'B2', 'B3' => 'grade-B',
                        'C', 'C4', 'C5', 'C6' => 'grade-C',
                        'D', 'D7', 'E8' => 'grade-D',
                        default => 'grade-F'
                    };
                @endphp
                <tr class="{{ $gradeClass }}">
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $b->admissionno ?? '-' }}</td>
                    <td style="text-align:left;">{{ $b->lname ?? '' }}, {{ $b->fname ?? '' }}</td>
                    @foreach($assessments as $a)
                        <td>{{ number_format($assessmentScores[$a->id], 1) }}</td>
                    @endforeach
                    <td><strong>{{ number_format($rowTotal, 1) }}</strong></td>
                    <td><strong>{{ $b->grade ?? '-' }}</strong></td>
                    <td>{{ number_format($b->cum ?? 0, 1) }}</td>
                    <td>{{ $b->position ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature">
        <div>____________________<br>Subject Teacher</div>
        <div>____________________<br>Principal / Admin</div>
        <div>____________________<br>Date</div>
    </div>

    <div class="footer">
        Generated by Admin on {{ date('F j, Y, g:i a') }} | Powered by School Management System
    </div>
</body>
</html>
